# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:#DA627D)\
$directory\
[ÓÇ∞](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_commit\
$git_status\
$git_state\
$terraform\
[ÓÇ∞](fg:#FCA17D bg:#33658A)\
[$status](bg:#33658A)\
$cmd_duration\
[ÓÇ∞ ](fg:#33658A)\
$line_break\
\\$ \
"""

# Not supported on bash
right_format = """
[ÓÇ≤](fg:#9A348E)
(\
($nix_shell${custom.nix-shell})\
)\
[ÓÇ≤](bg:#9A348E fg:#86BBD8)\
(\
$deno\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
$zig\
)\
([ÓÇ≤](bg:#86BBD8 fg:#06969A)$docker_context)\
"""

# Enable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like ÔÑ† to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "fg:black bg:#DA627D"
format = "[ $path ]($style)"
repo_root_style = "fg:black bg:#DA627D bold"
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[ ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "Ôúò "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ÔúòÔÑ™ "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important Ôúò " = " ÔúòÔÑ™ "

[c]
symbol = "Óòû "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[cmd_duration]
# style = "bg:#9A348E"
style = "bg:#33658A"
format = '[$duration Ôâí ]($style)'

[deno]
symbol = "ü¶ï "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = "Ôåà "
style = "bg:#06969A"
format = '[ $symbol$context ]($style) $path'

[elixir]
symbol = "Óâµ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = "Óò¨ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = "Ôêò "
style = "fg:black bg:#FCA17D"
format = '[ $symbol$branch]($style)'

[git_commit]
style = "fg:black bg:#FCA17D"
format = '[(@$hash)( $tag)]($style)'
tag_symbol = "ÔÄ´ "
only_detached = true
tag_disabled = false

[git_state]
style = "fg:black bg:#FCA17D"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[git_status]
style = "fg:black bg:#FCA17D"
format = "[( $all_status$ahead_behind\b) ]($style)"
conflicted = 'ÔÅó $count '
stashed = 'ÔÄú $count '
deleted = 'Ô¨í $count '
renamed = '¬ª$count '
modified = 'ÔëÄ $count '
# staged = 'ÔÅò $count '
staged = 'Ôò¥ $count '
# untracked = 'ÔÅô $count '
untracked = ''
ahead = '‚á°$count '
behind = '‚á£$count '
diverged = '‚á°$ahead_count ‚á£$behind_count '
# up_to_date = 'ÔÅù '
up_to_date = '‚áï '

[golang]
symbol = "Óòß "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = "Óù∑ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[java]
symbol = "Óâñ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = "Óò§ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = "Óúò"
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "Ôö§ "
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[nix_shell]
symbol = "Ôãú"
style = "bg:#9A348E"
format = '[ $symbol DEVSHELL \($state\) ]($style)'

[custom.nix-shell]
command = '''
echo "${PATH//:/$'\n'}" | sed -En 's#^/nix/store/[a-z0-9]+-([^/]+).*$#\1#p' | awk '$0 != "source" {printf "%s%s",sep,$0; sep="|"}'
'''
when = '''
[ -z "$IN_NIX_SHELL" -a -n "$(echo "${PATH//:/$'\n'}" | sed -En 's#^/nix/store/[a-z0-9]+-([^/]+).*$#\1#p' | grep -v 'source')" ]
'''
shell = ["bash", "-c"]
use_stdin = false
description = "Detect inside Nix Shell"
symbol = "Ôãú"
style = "bg:#9A348E"
format = '[ $symbol SHELL( \($output\)) ]($style)'

[rust]
symbol = "Óû®"
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[status]
# styling bug: https://github.com/starship/starship/issues/4090
disabled = false
symbol = "‚úò $int"
success_symbol = "‚úì"
recognize_signal_code = true
style = "bg:#33658A"
format = ' $symbol $common_meaning(SIG$signal_name) '
pipestatus_separator = "\b|"
pipestatus = true
pipestatus_format = '[\[$pipestatus\]]($style) => $symbol $common_meaning(SIG$signal_name) '

[terraform]
symbol = "Û±Å¢"
style = "fg:black bg:#FCA17D"
format = '[| $symbol $workspace ]($style)'

[zig]
style = "fg:black bg:#86BBD8"
format = '[ $symbol($version) ]($style)'
